version: '3.4'

services:
  identifier:
    image: semtech/mu-identifier:1.9.1
    links:
      - dispatcher:dispatcher
  dispatcher:
    image: semtech/mu-dispatcher:2.0.0
    links:
      - resource:resource
    volumes:
      - ./config/dispatcher:/config
  virtuoso:
    image: tenforce/virtuoso:1.3.2-virtuoso7.2.2
    environment:
      SPARQL_UPDATE: "true"
      DEFAULT_GRAPH: "http://mu.semte.ch/application"
    volumes:
      - ./data/db:/data
      - ./config/virtuoso/virtuoso.ini:/data/virtuoso.ini
  resource:
    image: semtech/mu-cl-resources:1.20.0
    links:
      - database:database
    volumes:
      - ./config/resources:/config
  database:
    image: cecemel/mu-authorization:0.6.0-beta.8
    environment:
      MU_SPARQL_ENDPOINT: "http://virtuoso:8890/sparql"
    volumes:
      - ./config/authorization:/config
  deltanotifier:
    image: cecemel/delta-notifier:0.2.0-beta.2
    volumes:
      - ./config/delta:/config
  file:
    image: semtech/mu-file-service:3.1.0
    volumes:
      - ./data/files:/share
  files-consumer:
      image: lblod/delta-consumer-single-graph-maintainer:0.4.1
      environment:
        INGEST_GRAPH: 'http://mu.semte.ch/graphs/synced-files'
        SYNC_BASE_URL: 'https://stub.endpoint/'
        SERVICE_NAME: 'files-consumer'
        SYNC_FILES_PATH: '/sync/deltas/files/'
        SYNC_DATASET_SUBJECT: "http://data.lblod.info/datasets/delta-producer/dumps/NotApplicableNow"
        INITIAL_SYNC_JOB_OPERATION: "http://redpencil.data.gift/id/jobs/concept/JobOperation/deltas/consumer/initialSync/NotApplicableNow"
        JOB_CREATOR_URI: "http://data.lblod.info/services/id/files-consumer"
        DISABLE_INITIAL_SYNC: 'true'
        BYPASS_MU_AUTH_FOR_EXPENSIVE_QUERIES: 'true'
        KEEP_DELTA_FILES: 'true'
        DELTA_FILE_FOLDER: '/consumer-json-files'
        WAIT_FOR_INITIAL_SYNC: 'false'
      volumes:
        - ./data/files/consumer-files/:/consumer-files/
